version: '3.7'

volumes:
  content-data-api-tmp:

x-content-data-api: &content-data-api
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: content-data-api
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - content-data-api-tmp:/govuk/content-data-api/tmp
  working_dir: /govuk/content-data-api

services:
  content-data-api-lite: &content-data-api-lite
    <<: *content-data-api
    depends_on:
      - postgres-13
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/content-data-api"
      TEST_DATABASE_URL: "postgresql://postgres@postgres-13/content-data-api-test"
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"

  content-data-api-app: &content-data-api-app
    <<: *content-data-api-lite
    expose:
      - "3000"
    depends_on:
      - nginx-proxy
      - postgres-13
    command: bin/rails s --restart
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/content-data-api"
      VIRTUAL_HOST: content-data-api.dev.gov.uk
      BINDING: 0.0.0.0
