version: '3.7'

volumes:
  manuals-frontend-tmp:

x-manuals-frontend: &manuals-frontend
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: manuals-frontend
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - manuals-frontend-tmp:/govuk/manuals-frontend/tmp
  working_dir: /govuk/manuals-frontend

services:
  manuals-frontend-lite:
    <<: *manuals-frontend

  manuals-frontend-app: &manuals-frontend-app
    <<: *manuals-frontend
    depends_on:
      - router-app
      - content-store-app
      - static-app
      - nginx-proxy
    environment:
      ASSET_HOST: manuals-frontend.dev.gov.uk
      VIRTUAL_HOST: manuals-frontend.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  manuals-frontend-app-live:
    <<: *manuals-frontend-app
    depends_on:
      - nginx-proxy
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: manuals-frontend.dev.gov.uk
      HOST: 0.0.0.0
