version: '3.7'

x-manuals-frontend: &manuals-frontend
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: manuals-frontend
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/manuals-frontend

services:
  manuals-frontend-lite:
    <<: *manuals-frontend
    privileged: true

  manuals-frontend-app: &manuals-frontend-app
    <<: *manuals-frontend
    depends_on:
      - router-app
      - content-store-app
      - static-app
      - nginx-proxy
    environment:
      GOVUK_ASSET_ROOT: manuals-frontend.dev.gov.uk
      VIRTUAL_HOST: manuals-frontend.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  manuals-frontend-app-draft:
    <<: *manuals-frontend-app
    depends_on:
      - router-app-draft
      - content-store-app-draft
      - static-app-draft
      - nginx-proxy
    environment:
      GOVUK_ASSET_ROOT: draft-manuals-frontend.dev.gov.uk
      VIRTUAL_HOST: draft-manuals-frontend.dev.gov.uk
      PLEK_HOSTNAME_PREFIX: "draft-"
      HOST: 0.0.0.0

  manuals-frontend-app-live:
    <<: *manuals-frontend-app
    depends_on:
      - nginx-proxy
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: manuals-frontend.dev.gov.uk
      HOST: 0.0.0.0
