version: '3.7'

x-signon: &signon
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: signon
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/signon

services:
  signon-lite:
    <<: *signon
    privileged: true
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: "mysql2://root:root@mysql/signon_development"
      TEST_DATABASE_URL: "mysql2://root:root@mysql/signon_test"
      REDIS_HOST: redis

  signon-app:
    <<: *signon
    depends_on:
      - mysql
      - nginx-proxy-app
      - redis
    environment:
      DATABASE_URL: "mysql2://root:root@mysql/signon_development"
      VIRTUAL_HOST: signon.dev.gov.uk
      HOST: 0.0.0.0
      REDIS_HOST: redis
    ports:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid
