version: '3.7'

x-publisher: &publisher
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: publisher
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/publisher

services:
  publisher-lite:
    <<: *publisher
    privileged: true
    depends_on:
      - redis
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo/publisher"
      TEST_MONGODB_URI: "mongodb://mongo/publisher-test"
      REDIS_URL: redis://redis

  publisher-app: &publisher-app
    <<: *publisher
    depends_on:
      - redis
      - mongo
      - nginx-proxy-app
      - publishing-api-app
      - calendars-app
      - link-checker-api-app
    environment:
      MONGODB_URI: "mongodb://mongo/publisher"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: publisher.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid

  publisher-app-e2e:
    <<: *publisher-app
    depends_on:
      - redis
      - mongo
      - publisher-worker
      - nginx-proxy-app
      - publishing-api-app-e2e
      - calendars-app
      - link-checker-api-app

  publisher-worker:
    <<: *publisher
    depends_on:
      - redis
      - mongo
      - nginx-proxy-app
      - publishing-api-app-e2e
    environment:
      MONGODB_URI: "mongodb://mongo/publisher"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
