version: '3.7'

volumes:
  maslow-tmp:

x-maslow: &maslow
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: maslow
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - maslow-tmp:/govuk/maslow/tmp
  working_dir: /govuk/maslow

services:
  maslow-lite:
    <<: *maslow
    depends_on:
      - mongo-3.6
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/maslow"
      TEST_MONGODB_URI: "mongodb://mongo-3.6/maslow-test"

  maslow-app: &maslow-app
    <<: *maslow
    depends_on:
      - mongo-3.6
      - nginx-proxy
      - publishing-api-app
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/maslow"
      VIRTUAL_HOST: maslow.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
