version: '3.7'

x-special-route-publisher: &special-route-publisher
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: special-route-publisher
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/special-route-publisher

services:
  special-route-publisher-lite:
    <<: *special-route-publisher
