version: '3.7'

x-bouncer: &bouncer
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: bouncer
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/bouncer

services:
  bouncer-lite:
    <<: *bouncer
    depends_on:
      - postgres-13
    environment:
      TEST_DATABASE_URL: "postgresql://postgres@postgres-13/transition_test"
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"

  bouncer-app:
    <<: *bouncer
    depends_on:
      - postgres-13
      - nginx-proxy
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/transition"
      VIRTUAL_HOST: bouncer.dev.gov.uk,bouncer-redirect.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "8080"
    command: bundle exec mr-sparkle --force-polling
