version: '3.7'

x-government-frontend: &government-frontend
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: government-frontend
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/government-frontend

services:
  government-frontend-lite:
    <<: *government-frontend
    privileged: true

  government-frontend-app: &government-frontend-app
    <<: *government-frontend
    depends_on:
      - router-app
      - content-store-app
      - static-app
    environment:
      GOVUK_ASSET_ROOT: government-frontend.dev.gov.uk
      VIRTUAL_HOST: government-frontend.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  government-frontend-app-draft:
    <<: *government-frontend-app
    depends_on:
      - router-app-draft
      - content-store-app-draft
      - static-app-draft
    environment:
      GOVUK_ASSET_ROOT: draft-government-frontend.dev.gov.uk
      VIRTUAL_HOST: draft-government-frontend.dev.gov.uk
      PLEK_HOSTNAME_PREFIX: "draft-"
      HOST: 0.0.0.0

  government-frontend-app-live:
    <<: *government-frontend-app
    depends_on:
      - nginx-proxy-app
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: government-frontend.dev.gov.uk
      HOST: 0.0.0.0
