version: '3.7'

x-calendars: &calendars
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: calendars
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/calendars

services:
  calendars-lite:
    <<: *calendars

  calendars-app: &calendars-app
    <<: *calendars
    depends_on:
      - router-app
      - content-store-app
      - static-app
      - nginx-proxy
    environment:
      GOVUK_ASSET_ROOT: calendars.dev.gov.uk
      VIRTUAL_HOST: calendars.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  calendars-app-draft:
    <<: *calendars-app
    depends_on:
      - router-app-draft
      - content-store-app-draft
      - static-app-draft
      - nginx-proxy
    environment:
      GOVUK_ASSET_ROOT: draft-calendars.dev.gov.uk
      VIRTUAL_HOST: draft-calendars.dev.gov.uk
      PLEK_HOSTNAME_PREFIX: "draft-"
      HOST: 0.0.0.0

  calendars-setup:
    <<: *calendars
    depends_on:
      - publishing-api-app-e2e

  calendars-app-live:
    <<: *calendars-app
    depends_on:
      - nginx-proxy
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: calendars.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
