version: '3.7'

x-content-publisher: &content-publisher
  build:
    context: .
    dockerfile: services/content-publisher/Dockerfile
  image: content-publisher
  volumes:
    - ..:/govuk:delegated
    - bundle:/usr/local/bundle
    - home:/home/build
  working_dir: /govuk/content-publisher

services:
  content-publisher-lite:
    <<: *content-publisher
    privileged: true
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/content-publisher"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/content-publisher-test"
      REDIS_URL: redis://redis

  content-publisher-backend: &content-publisher-backend
    <<: *content-publisher
    depends_on:
      - postgres
      - redis
      - publishing-api-backend
      - asset-manager-backend
      - nginx-proxy
      - content-store-live
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/content-publisher"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: content-publisher.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid

  content-publisher-e2e:
    <<: *content-publisher-backend
    depends_on:
      - postgres
      - redis
      - content-publisher-worker
      - publishing-api-e2e
      - asset-manager-e2e
      - nginx-proxy

  content-publisher-worker:
    <<: *content-publisher
    depends_on:
      - postgres
      - redis
      - publishing-api-e2e
      - asset-manager-e2e
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/content-publisher"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
