version: '3.7'

x-content-publisher: &content-publisher
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: content-publisher
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/content-publisher

services:
  content-publisher-lite:
    <<: *content-publisher
    privileged: true
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/content-publisher"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/content-publisher-test"
      REDIS_URL: redis://redis

  content-publisher-app: &content-publisher-app
    <<: *content-publisher
    depends_on:
      - postgres
      - redis
      - publishing-api-app
      - asset-manager-app
      - nginx-proxy
      - content-store-app
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/content-publisher"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: content-publisher.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  content-publisher-app-e2e:
    <<: *content-publisher-app
    depends_on:
      - postgres
      - redis
      - content-publisher-worker
      - publishing-api-app-e2e
      - asset-manager-app-e2e
      - nginx-proxy

  content-publisher-worker:
    <<: *content-publisher
    depends_on:
      - postgres
      - redis
      - publishing-api-app-e2e
      - asset-manager-app-e2e
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/content-publisher"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
