version: '3.7'

x-govuk_publishing_components: &govuk_publishing_components
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk_publishing_components
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/govuk_publishing_components

services:
  govuk_publishing_components-lite:
    <<: *govuk_publishing_components
    privileged: true

  govuk_publishing_components-app:
    <<: *govuk_publishing_components
    depends_on:
      - nginx-proxy-app
    environment:
      VIRTUAL_HOST: govuk-publishing-components.dev.gov.uk
    ports:
      - "9292"
    command: bundle exec rackup spec/dummy/config.ru --host 0.0.0.0
