version: '3.7'

x-travel-advice-publisher: &travel-advice-publisher
  build:
    context: .
    dockerfile: services/travel-advice-publisher/Dockerfile
  image: travel-advice-publisher
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/travel-advice-publisher

services:
  travel-advice-publisher-lite:
    <<: *travel-advice-publisher
    privileged: true
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: "mongodb://mongo/travel-advice-publisher"
      TEST_MONGODB_URI: "mongodb://mongo/travel-advice-publisher-test"
      REDIS_URL: redis://redis

  travel-advice-publisher-app: &travel-advice-publisher-app
    <<: *travel-advice-publisher
    depends_on:
      - mongo
      - redis
      - publishing-api-app
      - asset-manager-app
      - content-store-app
      - nginx-proxy-app
    environment:
      MONGODB_URI: "mongodb://mongo/travel-advice-publisher"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: travel-advice-publisher.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  travel-advice-publisher-app-e2e:
    <<: *travel-advice-publisher
    depends_on:
      - postgres
      - redis
      - travel-advice-publisher-worker
      - publishing-api-app-e2e
      - asset-manager-app-e2e
      - nginx-proxy-app

  travel-advice-publisher-worker:
    <<: *travel-advice-publisher
    depends_on:
      - mongo
      - redis
      - publishing-api-app-e2e
      - asset-manager-app-e2e
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/travel-advice-publisher"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
