version: '3.7'

volumes:
  hmrc-manuals-api-tmp:

x-hmrc-manuals-api: &hmrc-manuals-api
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: hmrc-manuals-api
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - hmrc-manuals-api-tmp:/govuk/hmrc-manuals-api/tmp
  working_dir: /govuk/hmrc-manuals-api

services:
  hmrc-manuals-api-lite:
    <<: *hmrc-manuals-api

  hmrc-manuals-api-app: &hmrc-manuals-api-app
    <<: *hmrc-manuals-api
    depends_on:
      - publishing-api-app
      - nginx-proxy
    environment:
      VIRTUAL_HOST: hmrc-manuals-api.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid
