version: '3.7'

x-smart-answers: &smart-answers
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: smart-answers
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/smart-answers

services:
  smart-answers-lite:
    <<: *smart-answers
    privileged: true

  smart-answers-app:
    <<: *smart-answers
    depends_on:
      - nginx-proxy-app
      - publishing-api-app
      - static-app
      - content-store-app
    environment:
      VIRTUAL_HOST: smart-answers.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s --restart
