version: '3.7'

x-tmp: &info-frontend
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: info-frontend
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/info-frontend

services:
  info-frontend-lite:
    <<: *info-frontend

  info-frontend-app: &info-frontend-app
    <<: *info-frontend
    depends_on:
      - router-app
      - content-store-app
      - static-app
      - nginx-proxy
    environment:
      ASSET_HOST: info-frontend.dev.gov.uk
      VIRTUAL_HOST: info-frontend.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid

  info-frontend-app-live:
    <<: *info-frontend-app
    depends_on:
      - nginx-proxy
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: info-frontend.dev.gov.uk
      HOST: 0.0.0.0
