version: '3.7'

volumes:
  authenticating-proxy-tmp:

x-authenticating-proxy: &authenticating-proxy
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: authenticating-proxy
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - authenticating-proxy-tmp:/govuk/authenticating-proxy/tmp
  working_dir: /govuk/authenticating-proxy

services:
  authenticating-proxy-lite:
    <<: *authenticating-proxy
    depends_on:
      - mongo-3.6
    environment:
      GOVUK_UPSTREAM_URI: http://draft-origin.dev.gov.uk
      MONGODB_URI: "mongodb://mongo-3.6/authenticating-proxy"
      TEST_MONGODB_URI: "mongodb://mongo-3.6/authenticating-proxy-test"

  authenticating-proxy-app: &authenticating-proxy-app
    <<: *authenticating-proxy
    depends_on:
      - mongo-3.6
      - nginx-proxy
      - router-app-draft
    environment:
      GOVUK_UPSTREAM_URI: http://draft-origin.dev.gov.uk
      MONGODB_URI: "mongodb://mongo-3.6/authenticating-proxy"
      VIRTUAL_HOST: authenticating-proxy.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
