version: '3.7'

x-travel-advice-publisher: &travel-advice-publisher
  build:
    context: .
    dockerfile: travel-advice-publisher/Dockerfile
  image: travel-advice-publisher
  volumes:
    - ..:/govuk:delegated
    - bundle:/usr/local/bundle
    - home:/home/build
  working_dir: /govuk/travel-advice-publisher

services:
  travel-advice-publisher-default:
    <<: *travel-advice-publisher
    privileged: true
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: "mongodb://mongo/travel-advice-publisher"
      TEST_MONGODB_URI: "mongodb://mongo/travel-advice-publisher-test"
      REDIS_URL: redis://redis

  travel-advice-publisher-backend: &travel-advice-publisher-backend
    <<: *travel-advice-publisher
    depends_on:
      - mongo
      - redis
      - publishing-api-backend
      - asset-manager-backend
      - content-store-live
      - nginx-proxy
    environment:
      MONGODB_URI: "mongodb://mongo/travel-advice-publisher"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: travel-advice-publisher.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid

  travel-advice-publisher-e2e:
    <<: *travel-advice-publisher
    depends_on:
      - postgres
      - redis
      - travel-advice-publisher-worker
      - publishing-api-e2e
      - asset-manager-e2e
      - nginx-proxy

  travel-advice-publisher-worker:
    <<: *travel-advice-publisher
    depends_on:
      - mongo
      - redis
      - publishing-api-e2e
      - asset-manager-e2e
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/travel-advice-publisher"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
