version: '3.7'

x-specialist-publisher: &specialist-publisher
  build:
    context: .
    dockerfile: services/specialist-publisher/Dockerfile
  image: specialist-publisher
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/specialist-publisher

services:
  specialist-publisher-lite:
    <<: *specialist-publisher
    privileged: true
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: "mongodb://mongo/specialist-publisher"
      TEST_MONGODB_URI: "mongodb://mongo/specialist-publisher-test"
      REDIS_URL: redis://redis

  specialist-publisher-app: &specialist-publisher-app
    <<: *specialist-publisher
    depends_on:
      - mongo
      - redis
      - nginx-proxy-app
      - publishing-api-app
      - asset-manager-app
      - email-alert-api-app
    environment:
      MONGODB_URI: "mongodb://mongo/specialist-publisher"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: specialist-publisher.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s --restart

  specialist-publisher-app-e2e:
    <<: *specialist-publisher-app
    depends_on:
      - mongo
      - redis
      - specialist-publisher-worker
      - publishing-api-app-e2e
      - asset-manager-app-e2e
      - email-alert-api-app
      - nginx-proxy-app

  specialist-publisher-worker:
    <<: *specialist-publisher
    depends_on:
      - mongo
      - redis
      - publishing-api-app-e2e
      - asset-manager-app-e2e
    environment:
      MONGODB_URI: "mongodb://mongo/specialist-publisher"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
