version: '3.7'

volumes:
  content-data-admin-tmp:
  content-data-admin-node-modules:

x-content-data-admin: &content-data-admin
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: content-data-admin
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - content-data-admin-tmp:/govuk/content-data-admin/tmp
    - content-data-admin-node-modules:/govuk/content-data-admin/node_modules
  working_dir: /govuk/content-data-admin

services:
  content-data-admin-lite:
    <<: *content-data-admin
    depends_on:
      - postgres-13
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/content-data-admin"
      TEST_DATABASE_URL: "postgresql://postgres@postgres-13/content-data-admin-test"
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"

  content-data-admin-app: &content-data-admin-app
    <<: *content-data-admin
    depends_on:
      - content-data-api-app
      - nginx-proxy
      - postgres-13
    expose:
      - "3000"
    command: bin/rails s --restart
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/content-data-admin"
      VIRTUAL_HOST: content-data-admin.dev.gov.uk
      BINDING: 0.0.0.0
