version: '3.7'

volumes:
  service-manual-publisher-tmp:
  service-manual-publisher-node-modules:

x-service-manual-publisher: &service-manual-publisher
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: service-manual-publisher
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - service-manual-publisher-tmp:/govuk/service-manual-publisher/tmp
    - service-manual-publisher-node-modules:/govuk/service-manual-publisher/node_modules
  working_dir: /govuk/service-manual-publisher

services:
  service-manual-publisher-lite:
    <<: *service-manual-publisher
    shm_size: 512mb
    depends_on:
      - postgres-13
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/service-manual-publisher"
      TEST_DATABASE_URL: "postgresql://postgres@postgres-13/service-manual-publisher-test"
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"

  service-manual-publisher-app: &service-manual-publisher-app
    <<: *service-manual-publisher
    depends_on:
      - postgres-13
      - publishing-api-app
      - nginx-proxy
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/service-manual-publisher"
      VIRTUAL_HOST: service-manual-publisher.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
