version: '3.7'

volumes:
  govuk_publishing_components-tmp:
  govuk_publishing_components-node-modules:

x-govuk_publishing_components: &govuk_publishing_components
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk_publishing_components
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - govuk_publishing_components-tmp:/govuk/govuk_publishing_components/spec/dummy/tmp
    - govuk_publishing_components-node-modules:/govuk/govuk_publishing_components/node_modules
  working_dir: /govuk/govuk_publishing_components

services:
  govuk_publishing_components-lite:
    <<: *govuk_publishing_components

  govuk_publishing_components-jasmine:
    <<: *govuk_publishing_components
    ports:
      - "8888:8888"
    command: bundle exec rake app:jasmine

  govuk_publishing_components-app:
    <<: *govuk_publishing_components
    depends_on:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: govuk-publishing-components.dev.gov.uk
    expose:
      - "9292"
    command: bundle exec rackup spec/dummy/config.ru --host 0.0.0.0
