version: '3.7'

volumes:
  mapit-pg:

x-mapit: &mapit
  build:
    context: .
    dockerfile: projects/mapit/Dockerfile
  image: mapit
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
  working_dir: /govuk/mapit

services:
  mapit-pg:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - mapit-pg:/var/lib/postgresql/data

  mapit-app:
    <<: *mapit
    depends_on:
      - mapit-pg
      - nginx-proxy
    environment:
      DJANGO_SECRET_KEY: 'secret'
      MAPIT_DB_HOST: 'mapit-pg'
      PGHOST: "mapit-pg"
      VIRTUAL_HOST: mapit.dev.gov.uk
    expose:
      - "8000"
    command: python ./manage.py runserver 0.0.0.0:8000
