version: '3.7'

x-calculators: &calculators
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: calculators
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/calculators

services:
  calculators-lite:
    <<: *calculators
    # Tests need the privileged flag
    privileged: true

  calculators-app: &calculators-app
    <<: *calculators
    depends_on:
      - router-app
      - content-store-app
      - static-app
    environment:
      GOVUK_ASSET_ROOT: calculators.dev.gov.uk
      VIRTUAL_HOST: calculators.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  calculators-app-draft:
    <<: *calculators-app
    depends_on:
      - router-app-draft
      - content-store-app-draft
      - static-app-draft
    environment:
      GOVUK_ASSET_ROOT: draft-calculators.dev.gov.uk
      VIRTUAL_HOST: draft-calculators.dev.gov.uk
      PLEK_HOSTNAME_PREFIX: "draft-"
      HOST: 0.0.0.0

  calculators-app-live:
    <<: *calculators-app
    depends_on:
      - nginx-proxy-app
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: calculators.dev.gov.uk
      HOST: 0.0.0.0
