version: '3.7'

x-short-url-manager: &short-url-manager
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: short-url-manager
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/short-url-manager

services:
  short-url-manager-lite:
    <<: *short-url-manager
    privileged: true
    depends_on:
      - redis
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo/short-url-manager"
      TEST_MONGODB_URI: "mongodb://mongo/short-url-manager-test"
      REDIS_HOST: redis

  short-url-manager-app: &short-url-manager-app
    <<: *short-url-manager
    depends_on:
      - redis
      - mongo
      - nginx-proxy-app
      - publishing-api-app
    environment:
      MONGODB_URI: "mongodb://mongo/short-url-manager"
      REDIS_URL: redis
      VIRTUAL_HOST: short-url-manager.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
