version: '3.7'

x-link-checker-api: &link-checker-api
  build:
    context: .
    dockerfile: services/link-checker-api/Dockerfile
  image: link-checker-api
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - bundle:/usr/local/bundle
    - home:/home/build
  working_dir: /govuk/link-checker-api

services:
  link-checker-api-lite:
    <<: *link-checker-api
    privileged: true
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/link-checker-api"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/link-checker-api-test"
      REDIS_URL: redis://redis

  link-checker-api-app: &link-checker-api-app
    <<: *link-checker-api
    depends_on:
      - link-checker-api-worker
      - nginx-proxy-app
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/link-checker-api"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: link-checker-api.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid

  link-checker-api-worker:
    <<: *link-checker-api
    depends_on:
      - postgres
      - redis
      - nginx-proxy-app
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/link-checker-api"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
