version: '3.7'

x-search-api: &search-api
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: search-api
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/search-api
  environment:
    RABBITMQ_HOSTS: rabbitmq
    RABBITMQ_VHOST: /
    RABBITMQ_USER: guest
    RABBITMQ_PASSWORD: guest
    REDIS_HOST: redis
    ELASTICSEARCH_URI: http://elasticsearch5:9200
    ELASTICSEARCH_B_URI: http://elasticsearch6:9200

services:
  search-api-lite:
    <<: *search-api
    depends_on:
      - redis
      - rabbitmq
      - elasticsearch6

  search-api-app: &search-api-app
    <<: *search-api
    depends_on:
      - nginx-proxy-app
      - redis
      - elasticsearch6
    environment:
      REDIS_HOST: redis
      ELASTICSEARCH_URI: http://elasticsearch5:9200
      ELASTICSEARCH_B_URI: http://elasticsearch6:9200
      VIRTUAL_HOST: search-api.dev.gov.uk, search.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bundle exec mr-sparkle --force-polling -- -p 3000

  search-api-setup:
    <<: *search-api
    depends_on:
      - publishing-api-app-e2e

  search-api-worker:
    <<: *search-api
    depends_on:
      - redis
      - rabbitmq
      - elasticsearch6
    command: bundle exec sidekiq -C ./config/sidekiq.yml

  search-api-listener-publishing-queue:
    <<: *search-api
    depends_on:
      - rabbitmq
    command: bundle exec rake message_queue:listen_to_publishing_queue

  search-api-listener-insert-data:
    <<: *search-api
    depends_on:
      - rabbitmq
    command: bundle exec rake message_queue:insert_data_into_govuk

  search-api-listener-bulk-insert-data:
    <<: *search-api
    depends_on:
      - rabbitmq
    command: bundle exec rake message_queue:bulk_insert_data_into_govuk

  search-api-app-e2e:
    <<: *search-api-app
    depends_on:
      - nginx-proxy-app
      - redis
      - elasticsearch6
      - search-api-worker
      - search-api-listener-publishing-queue
      - search-api-listener-insert-data
      - search-api-listener-bulk-insert-data
